version: '2'
services:
  demo:
    build: .
    ports:
     - '8101:8101'
    volumes:
     - .:/usr/src/app
     - ./.m2-cache:/home/root/.m2
    environment:
     - LIVE_PORT=8101
     - GLOBAL_JWT_SECRETS=TEST,TEST2
